config/routes.rb
Rails.application.routes.draw do

  get 'admins/welcome_admin'

  resources :semesters
  resources :groups
  resources :courses
  resources :tasks
  resources :users
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  resources :users
  delete 'logout' => 'sessions#destroy'
  get 'my_group' => 'students#my_group'
  get 'my_tasks' => 'students#my_tasks'
  get 'my_courses' => 'students#my_courses'
  get 'welcome' => 'students#index'
  get 'welcome_admin' => 'admins#index'
  get 'welcome_instructor' => 'instructors#index'
  get 'my_courses_instructor' => 'instructors#my_courses_instructor'
  get 'my_groups_instructor' => 'instructors#my_groups_instructor'
  get '404' => 'users#404'

  root 'sessions#new'

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :semester
  has_and_belongs_to_many :courses
  has_and_belongs_to_many :tasks
  has_and_belongs_to_many :users

  validates :name , presence: true,
                    length: {minimum: 5},
                    uniqueness: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_user
  before_action :require_admin

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @students = User.where(:id => params[:students_groups])
    @group.users << @students
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
  @group = Group.find(params[:id])
  @students = User.where(:id => params[:students_groups])
  @group.users.destroy_all
  @group.users << @students
    if @group.update(group_params)
      redirect_to groups_path
    else
      render 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  private
    def group_params
      params.require(:group).permit(:name, :semester_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="container">
  <%= form_for @group, class: "form-horizontal" do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@group.errors.count, "error") %> prohibited
        this group from being saved:
      </h2>
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
      <label class="control-label col-sm-2">Group Name:</label>
      <div class="col-sm-10">
        <%= f.text_field :name, class:"form-control" %>
      </div>
    </div>
    <br>
    <br>
    <br>
    <div class="form-group">
      <label class="control-label col-sm-2">Semester:</label>
      <div class="col-sm-10">
        <%= f.select :semester_id, options_for_select(Semester.all.map{ |s| [s.name, s.id] }) %>
      </div>
    </div>
    <br>
    <br>
    <br>
    <div class="form-group">
      <label class="control-label col-sm-2">Students:</label>
      <div class="col-sm-10">
        <%= select_tag "students_groups", options_from_collection_for_select(User.all.where(role: 'student'), 'id', 'full_name',@group.users.map{ |g| g.id }), :multiple => true %>
      </div>
    </div>
    <br>
    <br>
    <div class="form-group">
      <div align="center">
        <%= f.submit "Add Group", class: "btn btn-primary align-center" %>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<%= render 'form' %>

app/views/groups/index.html.erb
<div class="container">
  <h1> Groups </h1>
  <div class="container">
    <table class="table">
      <tr>
        <th> Group Name</th>
        <th> Semester</th>
        <th> Students</th>
        <th> Edit </th>
        <th> Delete </th>
      </tr>
      <% @groups.each do |group| %>
        <tr>
          <td> <%= group.name %> </td>
          <td> <%= group.semester.name%> </td>
          <td>
            <ul>
              <% group.users.each do |user| %>
              <li>
                <%= user.full_name %>
              </li>
              <% end %>
            </ul>
          </td>
          <td> <%= link_to "Edit", edit_group_path(group), class: "btn btn-warning align-center" %></td>
          <td> <%= link_to 'Destroy', group_path(group),
                    method: :delete,
                    data: { confirm: 'Are you sure?' },
                    class: "btn btn-danger align-center" %></td>
        </tr>
      <% end %>
    </table>
  </div>

</div>

app/views/groups/new.html.erb
<%= render 'form' %>