config/routes.rb
Rails.application.routes.draw do

  get 'admins/welcome_admin'

  resources :semesters
  resources :groups
  resources :courses
  resources :tasks
  resources :users
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  resources :users
  delete 'logout' => 'sessions#destroy'
  get 'my_group' => 'students#my_group'
  get 'my_tasks' => 'students#my_tasks'
  get 'my_courses' => 'students#my_courses'
  get 'welcome' => 'students#index'
  get 'welcome_admin' => 'admins#index'
  get 'welcome_instructor' => 'instructors#index'
  get 'my_courses_instructor' => 'instructors#my_courses_instructor'
  get 'my_groups_instructor' => 'instructors#my_groups_instructor'
  get '404' => 'users#404'

  root 'sessions#new'

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :semester
  has_many :tasks
  has_and_belongs_to_many :groups
  has_and_belongs_to_many :users

  validates :name , presence: true,
                    length: {minimum: 5},
                    uniqueness: true
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :semester
  has_and_belongs_to_many :courses
  has_and_belongs_to_many :tasks
  has_and_belongs_to_many :users

  validates :name , presence: true,
                    length: {minimum: 5},
                    uniqueness: true
end

app/models/semester.rb
class Semester < ActiveRecord::Base
  has_many :groups
  has_many :courses

  validates :name , presence: true,
                    length: {minimum: 5},
                    uniqueness: true

  validates :start_date , presence: true

  validates :end_date , presence: true

  validates :status , presence: true,
                      length: {maximum: 1}

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :course
  has_and_belongs_to_many :groups

  validates :title, presence: true

  validates :description, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_and_belongs_to_many :groups
  has_and_belongs_to_many :courses

  validates :first_name , presence: true,
                          length: {minimum: 4}

  validates :last_name ,presence: true,
                        length: {minimum: 4}

  validates :user_number ,presence: true,
                          length: {maximum: 5, minimum: 5},
                          allow_blank: true,
                          uniqueness: true

  validates :role , presence: true

  validates :age , presence: true


  def full_name
    "#{first_name} #{last_name}"
  end

  def admin?
    self.role == 'admin'
  end

  def instructor?
    self.role == 'instructor'
  end

  def student?
    self.role == 'student'
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :require_user
  def index
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :require_user
  before_action :require_admin

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    @groups = Group.where(:id => params[:courses_groups])
    @course.groups << @groups
    @users = User.where(:id => params[:courses_users])
    @course.users << @users
    if @course.save
      redirect_to courses_path
    else
      render 'new'
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
  @course = Course.find(params[:id])
  @groups = Group.where(:id => params[:courses_groups])
  @course.groups.destroy_all
  @course.groups << @groups
  @users = User.where(:id => params[:courses_users])
  @course.users.destroy_all
  @course.users << @users
    if @course.update(course_params)
      redirect_to courses_path
    else
      render 'edit'
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_path
  end

  private
    def course_params
      params.require(:course).permit(:name, :semester_id)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_user
  before_action :require_admin

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @students = User.where(:id => params[:students_groups])
    @group.users << @students
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
  @group = Group.find(params[:id])
  @students = User.where(:id => params[:students_groups])
  @group.users.destroy_all
  @group.users << @students
    if @group.update(group_params)
      redirect_to groups_path
    else
      render 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  private
    def group_params
      params.require(:group).permit(:name, :semester_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user
  before_action :require_instructor
  
  def index
    @courses = current_user.courses
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @groups = Group.where(:id => params[:groups_tasks])
    @task.groups << @groups
    if @task.save
      redirect_to tasks_path
    else
      render 'new'
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
  @task = Task.find(params[:id])
  @groups = Group.where(:id => params[:groups_tasks])
  @task.groups.destroy_all
  @task.groups << @groups
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render 'edit'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private
    def task_params
      params.require(:task).permit(:title, :description, :date_to_deliver, :course_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
  @user = User.find(params[:id])
    if @user.update(user_params)
      if current_user.student?
        redirect_to '/welcome'
      end
      if current_user.admin?
        redirect_to users_path
      end
      if current_user.instructor?
        redirect_to '/welcome_instructor'
      end
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:user_number, :first_name, :last_name, :password, :password_confirmation, :email, :phone, :role, :age)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/index.html.erb
<center>
  <h1> Welcome <%= current_user.first_name %> </h1>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" >TaskManager</a>
      </div>
      <div>
        <ul class="nav navbar-nav">
          <% if current_user %>
            <% if current_user.student? %>
              <li><%= link_to "Home", '/welcome' %></li>
            <% end %>
            <% if current_user.instructor? %>
              <li><%= link_to "Home", '/welcome_instructor' %></li>
            <% end %>
            <% if current_user.admin? %>
              <li><%= link_to "Home", '/welcome_admin' %></li>
            <% end %>
          <% end %>
          <% if current_user  && current_user.admin? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Semesters
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Semesters", semesters_path %></li>
              <li><%= link_to "New Semester", new_semester_path %></li>
            </ul>
          </li>
          <% end %>
          <% if current_user %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Groups
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if current_user && current_user.admin? %>
                <li><%= link_to "All Groups", groups_path %></li>
                <li><%= link_to "New Group", new_group_path %></li>
              <% elsif current_user.student? %>
                <li><%= link_to "My groups", my_group_path %></li>
              <% elsif current_user.instructor? %>
                <li><%= link_to "My groups", my_groups_instructor_path %></li>
              <% end %>
            </ul>
          </li>
          <% end %>
          <% if current_user %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Courses
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if current_user.admin? %>
                <li><%= link_to "All Courses", courses_path %></li>
                <li><%= link_to "New Course", new_course_path %></li>
              <% end %>
              <% if current_user.student? %>
                <li><%= link_to "My Courses", my_courses_path %></li>
              <% end %>
              <% if current_user.instructor? %>
                <li><%= link_to "My Courses", my_courses_instructor_path %></li>
              <% end %>
            </ul>
          </li>
          <% end %>
          <% if current_user  && current_user.instructor? || current_user.student? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Tasks
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if current_user.instructor? %>
                <li><%= link_to "All Tasks", tasks_path %></li>
                <li><%= link_to "New Task", new_task_path %></li>
              <% elsif current_user.student? %>
                <li><%= link_to "My Tasks", my_tasks_path %>
              <% end %>
            </ul>
          </li>
          <% end %>
          <% if current_user && current_user.admin?%>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Users
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Users", users_path %></li>
              <li><%=link_to "New User", new_user_path %></li>
            </ul>
          </li>
          <% end %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.first_name %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
            <% if current_user %>
              <li><%= link_to "Edit Profile" ,edit_user_path(current_user)%></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            <% else %>
              <li><%= link_to "Login", 'login'  %></li>
              <li><%= link_to "Signup", 'signup' %></li>
            <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <% end %>

<%= yield %>

</body>
</html>